site_name: Siminars Developer Center
site_description: Documentation to help you get started with Developing applications using the Siminars Platform
repo_url: https://github.com/Simversity
pages:
    - [index.md, Home]
    - [api.md, Api]
    - [party.md, Party]
    - [nginx.md, Nginx]
    - [about.md, About]
#theme: journal
theme: flatly
